openapi: 3.0.0
info:
  title: Campaign Management API
  version: 1.0.0
paths:
  /api/campaigns:
    get:
      summary: Get a list of campaigns
      responses:
        '200':
          description: A list of campaigns
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campaign'
  /api/campaigns/{id}:
    get:
      summary: Get detailed data for a single campaign
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detailed campaign data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignData'
components:
  schemas:
    Campaign:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
    CampaignData:
      type: object
      properties:
        campaignId:
          type: integer
        impressions:
          type: integer
        clicks:
          type: integer
        ctr:
          type: number
        spend:
          type: number
